"""empty message

Revision ID: 4774919bf9ae
Revises: 8ea4ebf5d3d7
Create Date: 2025-01-02 15:38:28.873121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4774919bf9ae'
down_revision: Union[str, None] = '8ea4ebf5d3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('isProMatch', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'isProMatch')
    # ### end Alembic commands ###
