services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    command:
      - 'php'
      - '-S'
      - '[::]:${ADMINER_PORT}'
      - '-t'
      - '/var/www/html'
    depends_on:
      - db

  migrate_tables:
    container_name: migrate_tables
    restart: no
    env_file:
      - .env
      - .env.database
    build:
      dockerfile: ../dockerfiles/migration/Dockerfile
      context: database
    depends_on:
      db:
        condition: service_healthy
