"""empty message

Revision ID: bf9acb0c978b
Revises: 4774919bf9ae
Create Date: 2025-01-02 22:35:21.209858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9acb0c978b'
down_revision: Union[str, None] = '4774919bf9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'date')
    # ### end Alembic commands ###
